# # Configuration for Rasa NLU.
# # https://rasa.com/docs/rasa/nlu/components/
# language: en

# pipeline: 
#   - name: SpacyNLP # loads the spacy language model
#     model: "en_core_web_md"
#     case_sensitive: False
#   - name: SpacyTokenizer # Tokenize sentences into docs
#   - name: SpacyFeaturizer # generate word embeddings
#     pooling: mean 
#   - name: RegexFeaturizer
#   - name: CRFEntityExtractor
#   - name: RegexEntityExtractor
#     case_sensitive: false
#     use_lookup_tables: true
#     use_regexes: true
#     use_word_boundaries: true
#   - name: EntitySynonymMapper
#   - name: SklearnIntentClassifier

# policies:
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
#   - name: RulePolicy

language: en
pipeline: 
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  - name: LexicalSyntacticFeaturizer
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DucklingEntityExtractor
    url: 'http://localhost:8000'
    dimensions: null
  - name: RegexEntityExtractor
    case_sensitive: false
    use_lookup_tables: true
    use_regexes: true
    use_word_boundaries: true
  - name: DIETClassifier
    epochs: 100
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1
policies:
  - name: AugmentedMemoizationPolicy
    max_history: 5
  - name: TEDPolicy
    max_history: 8
    epochs: 200
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True